[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "python3.11 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT server.app:app"
